export {
  STUDIO_CONTACT,
  STUDIO_EMAIL,
  STUDIO_PHONE,
  STUDIO_PHONE_TEL,
  STUDIO_LOCATION,
  STUDIO_EST,
  SOCIAL_INSTAGRAM,
  SOCIAL_FACEBOOK,
  SOCIAL_TIKTOK,
  PARENT_URL,
  KAYZ_URL,
  NAP_LINE,
  SISTER_SENTENCE,
  organizationJsonLd as studioJsonLd,
} from "@/lib/seo";

export const SHOW_SISTER_SHOPS = true;
