/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiCustomArtRouteImport } from './routes/api/custom-art'
import { Route as KitIdRouteImport } from './routes/kit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomArtRoute = ApiCustomArtRouteImport.update({
  id: '/api/custom-art',
  path: '/api/custom-art',
  getParentRoute: () => rootRouteImport,
} as any)
const KitIdRoute = KitIdRouteImport.update({
  id: '/kit/$id',
  path: '/kit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/api/custom-art': typeof ApiCustomArtRoute
  '/kit/$id': typeof KitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/api/custom-art': typeof ApiCustomArtRoute
  '/kit/$id': typeof KitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/api/custom-art': typeof ApiCustomArtRoute
  '/kit/$id': typeof KitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/custom'
    | '/login'
    | '/api/custom-art'
    | '/kit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/custom'
    | '/login'
    | '/api/custom-art'
    | '/kit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/custom'
    | '/login'
    | '/api/custom-art'
    | '/kit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CustomRoute: typeof CustomRoute
  LoginRoute: typeof LoginRoute
  ApiCustomArtRoute: typeof ApiCustomArtRoute
  KitIdRoute: typeof KitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/custom-art': {
      id: '/api/custom-art'
      path: '/api/custom-art'
      fullPath: '/api/custom-art'
      preLoaderRoute: typeof ApiCustomArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/$id': {
      id: '/kit/$id'
      path: '/kit/$id'
      fullPath: '/kit/$id'
      preLoaderRoute: typeof KitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CustomRoute: CustomRoute,
  LoginRoute: LoginRoute,
  ApiCustomArtRoute: ApiCustomArtRoute,
  KitIdRoute: KitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
